### ISSUE TITLE
ResInstDestroy 

### ISSUE THREAD

**Issue by mashaomin** [billwillman/UnityResourceMgr#1]
GameObject处于visable=false的状态下。不会执行OnDestroy方法

**Comment by billwillman** [comment]
这个我知道，但只要设置过一次过Active为True，无论后面是否为true都会调用OnDestroy，所以不要隐藏做Prefab，在代码里隐藏

**Comment by billwillman** [comment]
这个我知道，但只要设置过一次过Active为True，无论后面是否为true都会调用OnDestroy，所以不要隐藏做Prefab，在代码里隐藏

**Comment by billwillman** [comment]
ResInstDestroy已经做了自动判断以及设置
