### ISSUE TITLE
关于DLL热更新

### ISSUE THREAD

**Issue by optimisez** [billwillman/UnityResourceMgr#12]
请问下DLL热更新是不是只支持安卓平台下的Mono编译而不是IL2CPP? 还是就是DLL热更新不支持iOS平台?

**Comment by billwillman** [comment]
是的只支持MONO编译的，目前SO的没做。如果要支持IOS,请使用LUA

**Comment by optimisez** [comment]
请问下如果使用二进制差异的思路来开发更新补丁有没有办法做到代码更新?

**Comment by billwillman** [comment]
原则上是可以做到差异化，而且腾讯已经做到这一点，APK之间生成差异化，下载。不关心你是任何文件

**Comment by optimisez** [comment]
iOS也能做到么？ 要是可以的话就不需要搞lua了。

**Comment by billwillman** [comment]
IOS本身平台就是差异化更新，LUA不是做差异化的，而是可以快速更新
