### ISSUE TITLE
稳定性

### ISSUE THREAD

**Issue by douyouyisi** [billwillman/UnityResourceMgr#14]
这经过项目检验了吗 大佬

**Comment by billwillman** [comment]
目前这个项目已经在用了（项目已经在后期），而且内存过了腾讯TDR性能测试

**Comment by billwillman** [comment]
建议使用Unity 5.3.8P2的版本，因为这个版本以后AB的常驻已经很小了

**Comment by billwillman** [comment]
目前项目代码基本已经很少再修改了，只是某些周边一些小BUG的修复，例如：LoaderGroup之类的，核心底层基本长时间没有动过

**Comment by billwillman** [comment]
目前项目用的是资源管理，更新走的是腾讯GCloud更新
