### ISSUE TITLE
[注意事项和项目使用常见问题]中存在的问题

### ISSUE THREAD

**Issue by EnjoyLife24** [billwillman/UnityResourceMgr#15]
你好！
Wiki中提到的“3.Prefab上不要挂任何脚本，通过代码挂脚本，后面Dll更新会出问题。”

这个“不要挂任何脚本”是怎么理解的？

是指不要在预设体上挂我们用户自定义的脚本吗？（Unity自带的那些不需要更新的呢）

比如我有一个 UI 布局拉成预设体了，是指这个预设体及其下的所有的子GameObject上都不能往预设体上挂脚本吗？
还是只是指这个预设体根节点上不要挂任何脚本？？

很疑惑！

**Comment by billwillman** [comment]
例如：NGUI自带的脚本是可以的没问题的，但如果是项目中的UI逻辑脚本，不要直接绑到Prefab并保存文件，UIManager动态加载后动态绑定
