### ISSUE TITLE
打PC的包测试http链接很快就判断为超时了

### ISSUE THREAD

**Issue by m969** [billwillman/UnityResourceMgr#16]
if (DecConnectTimeOut(0.033f))
我把 0.033f 改为 timer 就好了，作者看看是为什么

**Comment by billwillman** [comment]
1.设置为0.033f,是假定了一帧最快需要0.033f,当然这个值是以30FPS作为参考，如果你渲染设置为60FPS，则，这种计算时间是快了一倍，怎么解决这个问题，两种方式，要么以设置FPS为准计算帧时间，60FPS就是1/60，或者加大参数里的连接超时最大判断时间（默认是5S我记得貌似，可以设置为10S或者更大）。
2.为什么使用固定时间，而非timer，因为当某些卡顿的情况，或者切后台等等情况下，会导致timer时间差比较大，而认为超时（这个跟TIMER的判断时机有关系），心跳包也要用这类机制。
3.可以尝试加大超时判断时间（在函数传入参数里
）

**Comment by billwillman** [comment]
另外增加isKeepAlive的参数，根据业务决定是否需要开启KEEPALIVE，默认参数是TRUE

**Comment by m969** [comment]
原来如此，多谢解答疑惑
