### ISSUE TITLE
ios真机测试资源更新失败几次后就不更新了

### ISSUE THREAD

**Issue by m969** [billwillman/UnityResourceMgr#17]
请问作者，我在ios真机上测试自动更新的流程，但是它在资源更新失败几次后就直接不更新了，我怀疑是更新失败的时候version.txt更新了但是ab资源包却没有更新，这种情况怎么处理比较好？
不知AutoUpdateClear是否可以解决，我先试试。

**Comment by billwillman** [comment]
新版本version.txt的更新是在AB完整更新完毕后才会写入。更新流程大致这样，服务器存放的是内容MD5的文件，然后下载本地，然后把内容MD5的文件更名为 文件名名MD5的文件（也就是本地文件），然后写入最新版本号到version.txt
