### ISSUE TITLE
关于依赖

### ISSUE THREAD

**Issue by lzl306567385** [billwillman/UnityResourceMgr#2]
```
    AssetBundleManifest manifest = BuildPipeline.BuildAssetBundles(exportDir, buildOpts, target);
    EditorUtility.UnloadUnusedAssetsImmediate();
```

这打包之后manifest是清空了
info.RebuildDependFiles(manifest);
以至于依赖没有获取
这是怎么回事

**Comment by billwillman** [comment]
你是自己去读取mainifest？
在BuildAssetBundles_5_x中，BuildAssetBundlesInfo_5_x完第一次后会导出一个配置文件记录好依赖关系，并不需要自己去读取mainifest(目前编译指令为二进制)，生成完依赖关系的配置文件后，再会将这个二进制文件打包成AB（使用增量打包，这个时候还没有删除manifest,增量打包需要这个），最后才RemoveBundleManifestFiles_5_x，删除掉manifest.
因为整个资源管理系统运行状态，并不需要manifest配置文件，所以打包完成后就会被删除

**Comment by billwillman** [comment]
另外，加载自定义的依赖配置，使用ResourceMgr.Instance.LoadConifgs

**Comment by billwillman** [comment]
已经答复你了。
mainifest，在游戏内并不需要使用，因为我们采用了自定义的依赖描述，另外删除是在最后一步做的。

在 2016-10-10 22:31:03，"lzl306567385" notifications@github.com 写道：

```
AssetBundleManifest manifest = BuildPipeline.BuildAssetBundles(exportDir, buildOpts, target);
EditorUtility.UnloadUnusedAssetsImmediate();
```

这打包之后manifest是清空了
info.RebuildDependFiles(manifest);
以至于依赖没有获取
这是怎么回事
