### ISSUE TITLE
读取AssetBundle

### ISSUE THREAD

**Issue by mzwhzzh** [billwillman/UnityResourceMgr#4]
你好，读取AssetBundle那里， StreamingAssets文件下的AssetBundles的内容为空， 能不能写点例子呢， 比较好理解一点

**Comment by billwillman** [comment]
原则上读取AssetBundle使用者不需要关心。使用ResourceMgr读取资源注意点：
1.路径全部用小写路径
2.路径是assets为根路径，也就是例如:你要读取assets/resources/xx.txt,你传入的路径就是resources/xx.txt
3.资源的文件名是带后缀的。

这些问题，注意事项中应该有些。

例子的话：默认场景有例子，如果需要我可以额外再补充几个

**Comment by mzwhzzh** [comment]
你好谢谢你的回复，默认场景是Main场景吗，我一运行Main场景就报错了。。

**Comment by billwillman** [comment]
一运行如果是提示你读取AssetBundle.xml两个红字错误，只是说你没有打AB而已，并不是真的会影响你程序Crash,如果打包成AB，则这两个红字会消失

**Comment by mzwhzzh** [comment]
谢谢，可以了。
