### ISSUE TITLE
请问我如何通过资源名获取包含这个资源的assetbundle

### ISSUE THREAD

**Issue by 867344633** [billwillman/UnityResourceMgr#5]
因为现在我用到了第三方的ui插件，而那个插件需要用到assetbundle，但你的资源框架的assetbundle是没有外部接口获取到的 ，能提供一个外部接口通过资源名获取到这个assetbundle文件吗

**Comment by billwillman** [comment]
可以，但你确定要用这样的功能么？设计的目的就是为了上层不知道AssetBundle的存在。已经在ResourceMgr提供了接口GetAssetBundleFileName

**Comment by billwillman** [comment]
但只有打了AB才能找到，建议还是在第三方UI上面修改代码，而不是指定AB

**Comment by 867344633** [comment]
知道是为了隐藏ab的存在

**Comment by 867344633** [comment]
第三方的ui也能从ab或者 resource上加载，但如果从ab上加载就必须获取到这个ab

**Comment by billwillman** [comment]
有个问题你要切记，更新以后目录位置是会变的，不确定你的Ui是否能读到可写目录Ab
