### ISSUE TITLE
请问 我 如果不希望resources下的某个文件或者某个文件夹不被打包怎么做

### ISSUE THREAD

**Issue by 867344633** [billwillman/UnityResourceMgr#6]
比如resources的fonts文件夹，shader文件夹等这些 都有可能是不需要打包的，那我该怎么解决，可否提供一个可忽略指定文件夹、文件名 打包的配置

**Comment by billwillman** [comment]
不需要做忽略配置，只需要建立一个目录internal/resources就可以了，当然，其实是有配置方法不过不是忽略目录，而是确定哪些目录打入

**Comment by billwillman** [comment]
Assets/internal/resources
