### ISSUE TITLE
关于引用计数的问题

### ISSUE THREAD

**Issue by GITHUB243884919** [billwillman/UnityResourceMgr#7]
1.记录每个AssetBundle有引用计数，当包含的Asset被加载时，引用计数+1，并且要通过Manifest找到这个Assetbundle依赖的所有Assetbundle，进行引用计数-1
2.记录每个Asset对应的AssetBundle
3.当释放Asset时候，要找到其Assetbundle，引用计数-1，并且要通过Manifest找到这个Assetbundle依赖的所有Assetbundle，进行引用计数-1
-----------------
这个思路对吗？
另外 ，能加下你QQ吗？

**Comment by billwillman** [comment]
没有这么简单，并不是+1，-1的简单方式，我在UWA群里的，你原来问过，我回到过你的
