### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by MarioHos** [billwillman/UnityResourceMgr#8]
你好，工程下载下来之后，报了一个错误，麻烦解决下
![tim 20170807172956](https://user-images.githubusercontent.com/10599579/29020924-52fd0f8c-7b96-11e7-9acb-df99fb49c132.png)

**Comment by billwillman** [comment]
报了什么错

**Comment by billwillman** [comment]
后面有空我把示例补上，示例不太足

**Comment by billwillman** [comment]
已经修正了

**Comment by MarioHos** [comment]
thanks
发自网易邮箱大师
在2017年08月23日 13:57，billwillman 写道： 已经修正了

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/billwillman/UnityResourceMgr","title":"billwillman/UnityResourceMgr","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/billwillman/UnityResourceMgr"}},"updates":{"snippets":[{"icon":"PERSON","message":"@billwillman in #8: 已经修正了"}],"action":{"name":"View Issue","url":"https://github.com/billwillman/UnityResourceMgr/issues/8#issuecomment-324229265"}}}
